# Orb 'circleci/aws-code-deploy@1.0' resolved to 'circleci/aws-code-deploy@1.0.1'
version: 2
jobs:
  build:
    working_directory: ~/majorproject-tues-18-30-5-tianchen-zhuang
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    steps:
    - checkout
    - run:
        command: |
          cd ~/majorproject-tues-18-30-5-tianchen-zhuang/BackEnd
          mvn dependency:go-offline
          mvn package
    - store_test_results:
        path: target/Backend/surefire-reports
    - store_artifacts:
        path: target/Backend/springboot-backend-0.0.1-SNAPSHOT.jar
    - checkout
    - run:
        command: |
          cd ~/majorproject-tues-18-30-5-tianchen-zhuang/FrontEnd
          sudo apt install curl
          curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          npm install
          npm test
    - persist_to_workspace:
        root: ~/majorproject-tues-18-30-5-tianchen-zhuang
        paths: .
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# orbs:
#   aws-code-deploy: circleci/aws-code-deploy@1.0
# version: 2.1
# jobs:
#   build:
#     working_directory: ~/majorproject-tues-18-30-5-tianchen-zhuang
#     docker:
#       - image: circleci/openjdk:8-jdk-stretch
# 
#     steps:
#       - checkout
#       - run:
#           command: |
#             cd ~/majorproject-tues-18-30-5-tianchen-zhuang/BackEnd
#             mvn dependency:go-offline
#             mvn package
# 
#       - store_test_results:
#           path: target/Backend/surefire-reports
# 
#       - store_artifacts:
#           path: target/Backend/springboot-backend-0.0.1-SNAPSHOT.jar
# 
#       - checkout
# 
#       - run:
#           command: |
#             cd ~/majorproject-tues-18-30-5-tianchen-zhuang/FrontEnd
#             sudo apt install curl
#             curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
#             sudo apt-get install -y nodejs
#             sudo apt-get install -y npm
#             npm install
#             npm test
# 
#       - persist_to_workspace:
#           root: ~/majorproject-tues-18-30-5-tianchen-zhuang
#           paths: .
# 
# deploy_application:
#   jobs:
#       - aws-code-deploy/deploy:
#           application-name: myApplication
#           bundle-bucket: myApplicationS3Bucket
#           bundle-key: myS3BucketKey
#           deployment-group: myDeploymentGroup
#           service-role-arn: myDeploymentGroupRoleARN