version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/node:8.9.1
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout:
          path: ~/majorproject-tues-18-30-5-tianchen-zhuang/BackEnd

      - restore_cache:
          key: BackEnd-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: BackEnd-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/springboot-backend-0.0.1-SNAPSHOT.jar

      - checkout:
          path: ~/majorproject-tues-18-30-5-tianchen-zhuang/FrontEnd

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            -
      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/majorproject-tues-18-30-5-tianchen-zhuang
          paths: .
