version: 2.1

jobs:
  build:
    working_directory: ~/majorproject-tues-18-30-5-tianchen-zhuang
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/majorproject-tues-18-30-5-tianchen-zhuang-0.0.1-SNAPSHOT.jar