version: 2
jobs:
  build:
    working_directory: ~/majorproject-tues-18-30-5-tianchen-zhuang
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/node:8.9.1

    steps:
      - checkout
      - run:
          command: |
            cd ~/majorproject-tues-18-30-5-tianchen-zhuang/BackEnd
            mvn dependency:go-offline
            mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/springboot-backend-0.0.1-SNAPSHOT.jar

      - checkout

      - run:
          command: |
            cd ~/majorproject-tues-18-30-5-tianchen-zhuang/FrontEnd
            npm install
            npm test

      - persist_to_workspace:
          root: ~/majorproject-tues-18-30-5-tianchen-zhuang
          paths: .
