version: 2.0

orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0

jobs:
  build:
    working_directory: ~/majorproject-tues-18-30-5-tianchen-zhuang
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - run:
          command: |
            cd ~/majorproject-tues-18-30-5-tianchen-zhuang/BackEnd
            mvn dependency:go-offline
            mvn package

      - store_test_results:
          path: target/Backend/surefire-reports

      - store_artifacts:
          path: target/Backend/springboot-backend-0.0.1-SNAPSHOT.jar

      - checkout

      - run:
          command: |
            cd ~/majorproject-tues-18-30-5-tianchen-zhuang/FrontEnd
            sudo apt install curl
            curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
            npm install
            npm test

      - persist_to_workspace:
          root: ~/majorproject-tues-18-30-5-tianchen-zhuang
          paths: .

deploy_application:
  jobs:
      - aws-code-deploy/deploy:
          application-name: TUES-18-30-5
          deployment-group: TUES-18-30-5-DeploymentGroup
          service-role-arn: arn:aws:iam::475933409365:role/CodeDeployServiceRole