version: 2.1
#https://circleci.com/docs/2.0/language-java-maven/

jobs:
  build:
    working_directory: ~/majorproject-tues-18-30-5-tianchen-zhuang
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - run:
          name: Generate cumulative pom.xml checksum
          command: |
            find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
            sort -o ~/pom-checksum ~/pom-checksum.tmp
          when: always
      - restore_cache:
          key: majorproject-tues-18-30-5-tianchen-zhuang-{{ checksum "~/pom-checksum" }}

      - run: mvn dependency:go-offline

          steps:
            - checkout
            - restore_cache:
                key: majorproject-tues-18-30-5-tianchen-zhuang-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline
            - save_cache:
                paths:
                  - ~/.m2
                key: majorproject-tues-18-30-5-tianchen-zhuang-{{ checksum "pom.xml" }}
            - run: mvn package

    - run:
        name: Save test results
        command: |
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
        when: always
    - store_test_results:
        path: ~/test-results
    - store_artifacts:
        path: ~/test-results/junit

